### ISSUE TITLE
Undefined index: baseurl

### ISSUE THREAD

**Issue by jahto** [Flyspray/flyspray#114]
I got "Notice: Undefined index: baseurl in C:\src\pgflyspray\includes\class.flyspray.php on line 806" when running setup/upgrade.php. Maybe related to the new session session handling? I don't understand much about it, otherwise I'd have fixed it myself. Not critical, upgrade works anyway.

**Comment by Psychokiller1888** [comment]
Yep got the same this morning when running upgrader

<div>-------- Message d'origine --------</div><div>De : Jouni Ahto <notifications@github.com> </div><div>Date :27/02/2015  17:28  (GMT+01:00) </div><div>A : Flyspray/flyspray <flyspray@noreply.github.com> </div><div>Objet : [flyspray] Undefined index: baseurl (#114) </div><div>
</div>I got "Notice: Undefined index: baseurl in C:\src\pgflyspray\includes\class.flyspray.php on line 806" when running setup/upgrade.php. Maybe related to the new session session handling? I don't understand much about it, otherwise I'd have fixed it myself. Not critical, upgrade works anyway.

**Comment by peterdd** [comment]
I have this one on this flyspray overview page /flyspray-master/index.php?do=toplevel&project=0

Notice: Undefined index: use_effort_tracking in /*****/flyspray-git/flyspray-master/scripts/toplevel.php on line 47 Notice: Undefined index: use_effort_tracking in /*****/flyspray-git/flyspray-master/scripts/toplevel.php on line 47

**Comment by Psychokiller1888** [comment]
Installer also is bugged, with that SESSION preimplant...

**Comment by jahto** [comment]
Interesting. When viewing all projects, $proj->prefs is not the same as when viewing s single project.

**Comment by peterdd** [comment]
Yeah, its a bit weired twisted in the code I think.

When viewing a overview page for all projects, why is there a single $proj object?
The $fs->projects array is filled 
Probably with the old project_id cookie there was always one (unneccassary) $proj object instantiated?

A meta redirect in toplevel.tpl also looks weired, because redirecting can be done serverside without an extra roundtrip

    /* If user has no projects, just redirect them to the index page of All Projects */
if (!$project_count): ?>
  <meta http-equiv="Refresh" content="0;url=/index.php?project=0&do=index" />
<?php endif; ?>

And it doesn't take care of $baseurl / BASEDIR (?)  (hardcoded /index.php)

**Comment by peterdd** [comment]
/* If user has no projects, just redirect them to the index page of All Projects */
    if (!$project_count): ?>
    <meta http-equiv="Refresh" content="0;url=/index.php?project=0&do=index" />
    <?php endif; ?>

**Comment by jahto** [comment]
I too don't really understand what that one is thought to be doing. Have to think about it later.

But I'm getting into the "undefined index". Have to add `$currentproj = new Project($project['project_id']);`, then check `if ($currentproj->prefs['use_effort_tracking'])`, put `$currentproj->prefs` somehow under `$projects[$project['project_id']]` so it gets passed to toplevel.tpl and then use that one for checks there. Just trying to get the syntax right.

**Comment by peterdd** [comment]
Mmh, if the request doesn't require a "current project" (in fact there is none prefered by project=0 param), why should we create a fake project class instance for just satisfying some stupid template? Sounds a bit like a workaround.

**Comment by jahto** [comment]
At least one per project preference (use_effort_tracking) is now checked for in both toplevel.php and toplevel.tpl, so it must be available even when project = 0. Future versions might need some other per project preferences, so best to get it right now.

Next thing is to see how it affects $user->perms in toplevel.tpl. If can't get it right during wednesday, I'll not try to show anything effort tracking related in 'all projects' toplevel view and leave it for 1.1. It's not a necessity for me.

**Comment by peterdd** [comment]
argh, i upgraded my real project tracking and now the column estimated effort is shown as 0:01 in task list overview and quick edit. I feel I have to reverse now and put in my backup. well, first I look in the db ..

**Comment by peterdd** [comment]
Ah, I think the values must be converted to seconds on upgrade

    UPDATE {task} SET estimated_effort=estimatet_effort*3600;

How we get sure it wasn't done before?

**Comment by jahto** [comment]
I'd say that we just can't be sure and it must be done manually. That's the price to be payed for using development version where things still can and will change...

**Comment by peterdd** [comment]
The upgrader needs definitely an output log to the user what changes are applied on upgrade.

And a info and button what to do after upgrade finished.

**Comment by Psychokiller1888** [comment]
Status?

**Comment by peterdd** [comment]
The upgrade process prints some output as info top the user version by version.
go to home after upgrade-button.

still old layout, untranslated, and not reviewed for real transactions (let some things brake in the upgrade process and see if db things changed or rolled back.)
