### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by Psychokiller1888** [Flyspray/flyspray#229]
Is the whole idea to make FS look horrible or what?

Actual: http://imgur.com/NSLbvHk
Old: http://imgur.com/LWiaikW

May I remind you a few comments on the web? Exemple: https://sourceforge.net/projects/flyspray/?source=directory (scroll down, check comments)

May I remind you that alpha is out and beta WAS planned around now? Ok, tbh, there won't be any beta release nor FS 1.0 for now

**Comment by jahto** [comment]
Solving all those problems with how Flyspray looks like will take a lot of time. Partly because we should agree on it... On the other hand, we've already ourselves fixed a lot of issues users had not even time to report because we found them first. Could you consider releasing alpha 2 instead? No beta until most issues on look-and-feel are resolved and we can agree upon how Flyspray will look like. I'm the easiest one to satisfy, because mostly I just don't care how it looks like, if it works, and if I really am not satisfied with something, I can always just create my own branch and do some finetuning to theme.css there and then use that one.

**Comment by Psychokiller1888** [comment]
I'm not about rewritting the whole theme now of course. What I mean is that i haven't been looking enough, or thought hey, it's an intermediary state, but it evolve from something not really famous, but not too bad, to something completly unstructured, where we have huge buttons, line breaks on infos, no guideline in visual effects etc etc etc. Been speaking with Jordan, the whole let's get rid of JS and stuffs isn't planned, he wants more integration with Ajax and Jquery, less clicks to do more. I totally agree that the look doesn't make the functions, but you can place me a ferarri engine in a Lada car I wouldn't drive it...

**Comment by jahto** [comment]
Yes, clicking twice for that is just stupid. What I mean, can we release something called at least alpha 2 and solve those kind of problems before going beta? The only thing really needed is making comments look a bit more sensible. Like the comment itself being below buttons for modifying/deleting it... Must be something related making the buttons forms and not putting attribute style:inline in correct places. I'll try that approach. We might can't count on peterdds co-operation for a few days, he seemed to take some changes quite deeply and should calm down.

**Comment by Psychokiller1888** [comment]
Oki, let's do so: I'll reowrk that comment part, finish whatever you were on core side and we release alpha 2 within this week. At least all sec bug fixes will be available

**Comment by jahto** [comment]
I'm fine with that. There's not much really really absolutely important anymore on the core side to work on that I have myself found. Of course there is... Need bug reports from someone. Just a few smaller things. Like maybe using $db->FetchRow and looping over result set instead of $db->FetchAllArray in two places, if it really saves some memory and adodb does not fetch the whole result set anyway before working on it.

**Comment by Psychokiller1888** [comment]
Well, that would be part 1

http://imgur.com/M4MeHuD

**Comment by jahto** [comment]
Now this gets quite interesting when trying to really create big data. Memory exhausted when trying to create notification message, although all notifications are turned offf and there's no-one to notify. 
```
$ time php -f CreateTestData.php
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32776 bytes) in C:\src\pgflyspray\includes\class.notify.php on line 490

real    15m46.374s
user    0m0.000s
sys     0m0.046s
```
Ok, then added `return` as the first line to method Notifications->Create. We spend a lot of time there. Memomy still exhausted.
```
$ time php -f CreateTestData.php
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32776 bytes) in C:\src\pgflyspray\includes\class.notify.php on line 490

real    15m46.374s
user    0m0.000s
sys     0m0.046s
```
Hasn't anybody in the whole history of Flyspray ever thought of adding just one small method, Database->Close($result) to free result sets?

The next thing I'm testing is a database with 150000 tasks and 750000 comments. We aren't ready for 1.0 until Flyspray survives at least that without crashing.

**Comment by Psychokiller1888** [comment]
Woot? If notifications are turned of this shouldn't happen first of all.

**Comment by jahto** [comment]
Yeah, I suspect there's something to be fixed there. Have to check my exact settings in database first, might have made a mistake myself. Anyway, it uses way too much time in finding there's no-one to notify about something and generating messages to be sent to no-one.

But first I think I'll start testing with big data and adding statements to free result sets.

**Comment by Psychokiller1888** [comment]
You that have been working on task inputs, is the preview part still exisitng? I mean, the actual method doesn't need a preview, it's wysiwyg...

**Comment by jahto** [comment]
Installations using dokuwiki formatting need still the preview button.

**Comment by Psychokiller1888** [comment]
Yeah, i'm readding it now, as i forgot it...

**Comment by Psychokiller1888** [comment]
Underline doesn't work in dokuwiki...

**Comment by jahto** [comment]
I can check dokuwiki formatting during easter holidays.

**Comment by Psychokiller1888** [comment]
Readded preview https://github.com/Flyspray/flyspray/pull/241

**Comment by jahto** [comment]
We've got some several memory usage problems with big data... Working on it, might take several days.

**Comment by Psychokiller1888** [comment]
Ok, so i'll wait for alpha 2

**Comment by jahto** [comment]
Oh, it happens only with CreateTestData... when $maxtasks = 150000, $maxcomments = 750000 and $maxattachments = 1500000, haven't been able to test Flyspray itself yet. Quite a stress test. But it will give good hints where we might have to do something to reduce memory usage in general. Found some hints about PHP's garbage collector reliability from the net. It's not reliable in older versions. Better manually just unset everything and also add __destruct method to every class we use, that unsets also everything used by a class instance. Thank god that I've been programming a lot in C/C++, I'm already used to clean up everything myself.

**Comment by peterdd** [comment]
@psycho:  Denying my changes on composerit sucked my power off. I implemented a new feature enabling to make the install process after unzipping complete over web browser, which you not saw a need for. Then you overwrote the solution that worked for me with a solution that works for you (well, partly If you would really reread that patch..) and denied the revert. Because I do after github changes a new flyspray install or upgrade on my testing environments to see I stumble immediatly over this issue and want that solved before doing any further work. Why not doing a solution that works for all?

@jahto: memory problems..  Could you identify the parts where memory usage suddenly jumped inside the code? I assumed it mostly happens when a db query result is fetched complete into a php variable or object instead of looping the dbresult with fetchRow for further processing.

@psycho: Yea I want flyspray ugly as hell :-( because I want to use it as project management for a big noncommercial web project.. I want it unusable and ugly as hell, because it is too easy with a simple tool and I got bored if it is too easy and like it to be punished.. :-( 
(ironic)

Ironic off:
I'm glad you addressed comment layout and I'm fine with it to let it look like on github comments.
For the comment section I wanted to use fonticons for edit and delete buttons, mainly because we have the awesome-fonts still loaded and so it is easy to manage the icons. You can see how I planned some usage of Icons at the end of theme.css.

For the button fix tell me what exactly you want to achieve and I hope I can help with a modified css rule that helps with fixing.
If you mean to put the "effacer" button beside the editer button, keep mind, putting a small delete icon beside a small edit icon could to easy lead to a 'fat finger' mistake on touch devices. I have no absolute best idea how to solve that, maybe the edit button on the left side of the comment and delete button( if user has right to delete comments) on the right side?

**Comment by peterdd** [comment]
I cannot do much work for flyspray now, only a bit watching and small things. This week work and easter and next week I'm in Croatia.

**Comment by Psychokiller1888** [comment]
I told you it doesn't work and the way it is now works for me. So reverting and put your stuffs would just do the same it did to you, but to me: Works for you, but not for me. So, a universal solution must be found, not just a simple revert.

If you check the latest changes on the comments part you'll see that i loaded github icon set that offers any icons we could ever use. The button rules, and I asked because you said you'd take care of them, are too intrisect, making the fake link buttons impossible per exemple. They need a total revamp, with basic rules and more classes for a "to be defined amount of different buttons in FS"

**Comment by peterdd** [comment]
Why do you care about what you didn't need before? Ruthless overwriting like in god mode is not nice. 

Why not repecting my needed config path (install on php5.3.* with SAFE_MODE off) and just make your path 
(no SAFE_MODE, php5.4+) working for you????

You startet "Cleanup after  setup", ok.
I will prepare a last pull request for fixing composerit.php and adding cleanup, so setup can be finished complete over web browser.

If that is not possible to merge to master (you can still make changes or comments, no problem), I'm forced to work with my own branches. But splitting a currently only 3-5 developer project isn't a good idea..

**Comment by Psychokiller1888** [comment]
What i didn't need before? Nobody needed composer before. Slow down your horses dude. You are doing the same by going back to your way: you'll respect only your stuffs and not mine. Find a common way. Composer installation page isn't hard to get: curl or php. You found a hack around that? Good, but it must work for the mass, not only for mac installs. Most server  and hosters are working on linux distro. Local devs are maybe on win/mac. some are running php 5.6. If They are security freeks afraid of letting anything through and disabling stuffs, that's not our problem. We must go the way the MASS is. The mass public has JS enabled, SAFE_MOD off etc etc etc etc etc

Now threatning me or anybody else isn't the good and right way to go. If that mess continues I swear i'll get rid once for all of composer in FS

**Comment by peterdd** [comment]
Grrr, we are talking 'aneinander vorbei' , don't know how to say in english.
Maybe we should sit together looking over the code and cleanup the misunderstandings?
Most of your rant is just a misunderstanding.

**Comment by Psychokiller1888** [comment]
Ne, mach doch deine Sache, ich lasse es durch und dann sehen wir ja zusammen wie Erwachsene falls irgendwas ned stimmt

**Comment by peterdd** [comment]
@jahto: Would it be ok to you to have my simple memory fix (patch-3) on flyspray master? It mainly replaces fetchAllArray be looping with fetchRow() and is very memoryfriendly. I test in my dev environment from now on with 25000 tasks on a 64MB for phpscripts allowed system.

The "complete permissions by SQL queries" is quite complex and needs much testing for every possible setting/config cases. Ideally tests are made for automatic tests for travis-ci.

**Comment by peterdd** [comment]
@psycho: ok!

**Comment by jahto** [comment]
I accept anything that makes Flyspray use less memory. Best solution in 2 places (get_task_list, get_events) would be using limit and offset in the query, but you mentioned something about a bug in adodb with that. I could not find any information about it. Can you confirm that it stll exists?

About those memory problems, I really can't find the cause. I just know that something eats memory. Maybe not so critical in reality, the problem manifests itself only when using createtestdata script. We hopefully don't do anything like that elsewehere. Anyway, finding the causes and fixing them would make Flyspray more memory friendly.

**Comment by peterdd** [comment]
currently I use memory_get_usage and die() in code to nail down the positions of memory increase in code.
