### ISSUE TITLE
ChangeLog not found

### ISSUE THREAD

**Issue by svetlyak40wt** [Flyspray/flyspray#299]
File `docs/CHANGELOG.md` has a link to http://www.flyspray.org/changelog but this page is not available anymore and I didn't find any changelog at this site.

Please, correct the link.

**Comment by peterdd** [comment]
I believe no one has written a summary of changes since the switch from the wiki pages to the current www.flyspray.org web site.

So at the moment the only you can do is reading 
https://github.com/Flyspray/flyspray/commits/master

and the history of resolved/closed bugs/features on bugs.flyspray.org

bugs.flyspray.org is currently not available due it was using MariaDB as Database, not MySQL. And during the upgrade 0.9.9.7 to github current version it hits a bug in MariaDB itself and upgrade rolled back sql transaction. I really hope former maintainer floele (who still hosts bugs.flyspray.org) can resolve this in the next days!

docs/* section needs review and fixing links, sure.

**Comment by svetlyak40wt** [comment]
Thank you for explanation.
