### ISSUE TITLE
Feature freeze and release

### ISSUE THREAD

**Issue by Psychokiller1888** [flyspray/flyspray#405]
Hi everybody!

After our successfull first Skype call, we've come up with a few dates regarding 1.0:

13.09.2015: **Feature freeze** Any new feature addition coming in after this date will be rejected and/or delayed to FS1.1

27.09.2015: **Beta 1.0** Releasing Beta 1.0

05.10.2015: **Flyspray 1.0** Release of the long awaited version

@peterdd @jahto  Please finish the parts you have started by the 13th of september

In the same time, we will migrate all of our communication ways to a central website. @jordanmendler proposed to set up a new server, while I shall set up the forum engine on it and Flo will redirect the DNS once it's made. This new central base will terminate any other, so that communication will take only thourgh it. Github reporting/ticket engine shall be turned off once everything is ready. For bug reporting we will exclusively use Flyspray. Our google mailing will remain and be used exclusively for important community annoucement, but no support will be provided on/via it

**Comment by jahto** [comment]
I have absolutely no parts that I have started and really should go into 1.0. In fact, I didn't have those since some time in April, but anyway committed one (rights checking in SQL) later, and another one (native language notifications) because I was asked to do it by @peterdd . The main thing is that we really release something, after that we can go forward and start to think about cleaning up the codebase, talk about formatting, maybe really make a move to using a templating engine (did we come up to any conclusion yesterday, I don't remember, I really had taken a few beers and glasses of white wine before the call, having the next day only half workday using a few hours from my overtime bank, still on the plus side). 

Thinking about the future, this community of volunteers doesn't seem to be something that can really be organized. But if it's possible, we should at least try to classify new feature proposals to 2 categories:

1. This is something I really want, it's absolutely needed, and I will implement it even if it means sleepless nights eating pizza, broken relationships, banging my head to the wall etc.
2. It can wait to the next version.

**Comment by jahto** [comment]
What's the current situation with the proposed central website for communication?

**Comment by Psychokiller1888** [comment]
Status: No time, and Jordan sent me ssh access to a server. We start picking up grapes this week and for the two next weeks. This month is wine production 24/24 6/7

**Comment by jahto** [comment]
Ok. I too have to start picking up the results of this year's gardening season, and then I'll travel a few weeks. See ya after mid of October, and then let's start discussing about the future.
