### ISSUE TITLE
Language installer problem

### ISSUE THREAD

**Issue by Neustradamus** [flyspray/flyspray#811]
@flyspray team, @peterdd, @jordanmendler: When we install Flyspray, there is a problem if the computer/browser of the person who installs is not English, for example.

Why?
Because the Flyspray Installer is not fully translated.

Solution: If translation line does not exist, it must be English default language.

Screenshot: https://i.ibb.co/1Z6TKpv/flyspray-installer-lang-problem.png

**Comment by peterdd** [comment]
Thanks for reminding me to do also tests with other browser defautl language settings. Yeah, seems the installer is not using the english fallback yet if there is no translation for the prefered language. I started to add this, but not finished it.

**Comment by peterdd** [comment]
Mmh, cannot reproduce with current github master as it uses the usual en-fallback when changing prefered language in browser (e.g. Firefox about:config 'intl.accept_languages') 
Which OS?

**Comment by peterdd** [comment]
@Neustradamus 

Ah, I see now. 

Some of the setup translation files like setup/lang/fr.php or setup/lang/it.php overwrite $language instead $translation, so there is no english fallback and the placeholders are shown.

setup/lang/fr.php:
```
<?php
$translation=array(
'available'          => 'verfügbar',
...
```
setup/lang/de.php:
```
<?php
$language=array(
'needcomposer'       => 'Vous avez besoin de certaines librairies installées par Composer.',
...
```

This may even be intentional made during development to force showing placeholders in the UI instead of english fallback translation strings when a translation file is incomplete like setup/lang/fr.php

Well, the whole translation part for the installer was just started, never in release state and probably helping text strings change more then the normal translation strings of Flyspray.

I change at least to having the fallback strings there..

**Comment by Neustradamus** [comment]
@peterdd: Thanks, now, if no translation lines, it will be english sources?

**Comment by peterdd** [comment]
oui

![flyspray_installation_french](https://github.com/flyspray/flyspray/assets/1839154/55b70b41-8dc1-4e32-b126-bc6e513709e1)

**Comment by Neustradamus** [comment]
@peterdd: Thanks to have solved it!
