### ISSUE TITLE
Free, empty spaces in Flyspray which need to be used

### ISSUE THREAD

**Issue by Neustradamus** [flyspray/flyspray#826]
@flyspray team, @peterdd,

Free, empty spaces in Flyspray which need to be used.

Can you remove the free space from task description:
- Screenshot: https://i.ibb.co/xfPYtqq/flyspray-little-block-and-cutted-task-description-sentence-text.png

Details:
- right description zone (number 0 on screenshot)

----------

Can you remove the free space from task comments:
- Screenshot: https://i.ibb.co/jgRCKzm/flyspray-little-block-and-cutted-comment-sentence-text.png

Details:
- left comments zone (number 1 on screenshot)
- right in comments zone (number 2 on screenshot)
- right comments zone (number 3 on screenshot)

Linked to:
- https://github.com/flyspray/flyspray/issues/806
- https://github.com/flyspray/flyspray/issues/824
- https://github.com/flyspray/flyspray/issues/825

**Comment by peterdd** [comment]
I once made intentional a CSS rule for that to improve readability.

![flyspray_readability](https://github.com/flyspray/flyspray/assets/1839154/3a5b8bb6-5711-4a49-9d4c-ecaf7aa33a3f)

You could simply override that CSS in a custom theme. (number 0 and number 3)

Well, for number 1 and 2 I'm open for layout ideas. There was also a wish to show comments on wide screen beside task detail description. FS#2548

**Comment by CaraesNaur** [comment]
In the first screenshot, that space is occupied by task dependencies if any are present.

The changes I'm working on in #887 applies `max-width: 50%` on `#taskdetailsfull`, so nothing should be cut off.  The rule @peterdd mentioned is still present, and I think should remain for readability reasons on *very* wide screens.  Although, I could change `#taskdetailsfull` to `max-width: 45em` instead (need room for margin+padding).

This is one of the places where I've implemented flexbox, as described in #887.

There are two occurrences of `word-wrap: anywhere` in `theme.css`, both in conjunction with `word-wrap: break-word` and accompanied by comments stating "css3, ff65+".  This is allowing the browser to break *within* words.

`word-wrap` is non-standard, browsers usually treat it as an alias of `overflow-wrap`.

@Neustradamus please confirm exactly what is happening, because the text as shown is redacted.

* Are the text lines being truncated, overflowing the container?
* Are unwanted line breaks being inserted within words, but otherwise wrapping as expected?

Either way, I think `word-wrap: anywhere` should be removed.  The rules it is used are already generous enough for general usage.

---
In the second screenshot:

Area 1 is where the user avatar is displayed.  Also notice the pointed nub on the comment header pointing to where the avatar would be.

I presume this install doesn't use avatars and it would be preferred if no remnants of them are shown.  I can see a case for a preference that enables/toggles avatars, which would be the foundation of the only real way to achieve that globally.

This is another place where flexbox has been used in #887 .

Even in `master`, comment avatars can be hidden with `.comment_avatar: { display: none; }` and the pointer nub can be removed by omitting these rules:

    div.comment_container .comment:before {}
    div.comment_container .comment:after {}

Area 2 exists because `.comment` has a declared width of `700px`.  I don't see this as a problem as this limit keeps comments readable.

Area 3 comes from the comment preview using the same `max-width` as above, for the same reason.

---

Studies have shown there is an ideal range of line width that improves reading comprehension and reduces eye strain, at least for Western languages.  That ideal range is 2 to 3 alphabets (that is, all alphabet letters in sequence, repeated).

Based on the English alphabet of 26 characters, and assuming the average character width is `.75em`, the ideal range comes to about 40 to 50 `em`.  The English alphabet is rather small among European languages, so setting that `max-width` closer to 50 is arguably an improvement all around.

**Comment by Neustradamus** [comment]
@peterdd, @CaraesNaur: Do not forget to remove all "spaces" (empty places).

It is important to have good sentences, not cutted, in all the page, all the monitor/screen.
Beautiful default themes.

**Comment by Neustradamus** [comment]
@peterdd, @CaraesNaur: All spaces have been removed?
Sentences are complete now, not cutted?

Recall my historical screenshots:
- https://i.ibb.co/xfPYtqq/flyspray-little-block-and-cutted-task-description-sentence-text.png
- https://i.ibb.co/jgRCKzm/flyspray-little-block-and-cutted-comment-sentence-text.png

**Comment by peterdd** [comment]
GH closed it automatically? :-/

No, just the avatar hide when disabled.
