### ISSUE TITLE
Update From Flyspray 0.9.9.5.1  TO Last release 

### ISSUE THREAD

**Issue by malekbenz** [flyspray/flyspray#827]
Hello, I want upgrate my Flyspray 0.9.9.5.1 to the last release , I want just to know if I can do it without any break changes.
to mention that I want to migrate to flyspray-1.0-rc10

**Comment by Neustradamus** [comment]
@malekbenz: Before all migrations please do a backup of your files and your database.
And please look your .htaccess (rules...)
Do not forget if you have done customizations.

It is important to do the update to this latest RC version to fix CVEs, but a lot of people have not done because it is specified "RC", I have requested to have a "Stable" build:
- https://github.com/flyspray/flyspray/issues/805

Note: Since 1.0-RC10, there are 130 commits more in master branch:
- https://github.com/flyspray/flyspray/releases/tag/v1.0-rc10

@peterdd has not create a new build...

**Comment by aducom** [comment]
You can create a build of your own locally and apply the vendor stuff. The instruction works well and I managed to get things upgraded to the latest version supporting PHP 8.1.

However, there is some maintenance required as composer reports issues:
Package dapphp/securimage is abandoned, you should avoid using it. No replacement was suggested.
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.

But besides that, things seem to work.

**Comment by dolenec** [comment]
> You can create a build of your own locally and apply the vendor stuff. The instruction works well and I managed to get things upgraded to the latest version supporting PHP 8.1.
> 
> However, there is some maintenance required as composer reports issues:
> Package dapphp/securimage is abandoned, you should avoid using it. No replacement was suggested.
> Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
> Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
> 
> But besides that, things seem to work.

So.. PHP 8.1 would work? You tested it?

**Comment by Neustradamus** [comment]
@peterdd: Can you create the RC11 this weekend?

A new guy, @dolenec would like to test too.

Thanks in advance.

**Comment by dolenec** [comment]
If you could prepeare it would be great..

Probably and my only concern is regarding update.. Currently using 0.9.x version for many years on PHP 7.2. Now it's time to update it and to start using PHP 8.1.27.

**Comment by Neustradamus** [comment]
@malekbenz, @aducom, @dolenec: Flyspray 1.0 RC11 is out!
- https://github.com/flyspray/flyspray/releases/tag/v1.0-rc11

Time to update your version ^^
Please do a backup before.
Please inform if it is good for you or if you have a problem.

**Comment by aducom** [comment]
I already managed to install on php 8.1ba while ago. Are there functional changes or just a full package now? Otherwise upgrade has no effect.B.r. Albert Op 29 jan. 2024 22:57 schreef Neustradamus ***@***.***>:
@malekbenz, @aducom, @dolenec: Flyspray 1.0 RC11 is out!
https://github.com/flyspray/flyspray/releases/tag/v1.0-rc11
Time to update your version ^^
Please do a backup before.
Please inform if it is good for you or if you have a problem.

**Comment by dolenec** [comment]
Confirm that upgrade went with no problem at all. Now using 1.0 rc11 with PHP 8.1.27.

Thank you.

**Comment by peterdd** [comment]
Nice to hear.

Notice that 1.0-rc10 to 1.0-rc11 has a regression: Managing categories is not working. See #856
