### ISSUE TITLE
Changing Default due in Version for new tasks is not working!

### ISSUE THREAD

**Issue by ctoabidmaqbool** [flyspray/flyspray#879]
Changing the `Default due in Version for new tasks` is not working.

![image](https://github.com/flyspray/flyspray/assets/10474725/177ba845-dd7d-4e5c-b3b0-404090fd96ea)

It's showing default category, e.g. **Undesided**

![image](https://github.com/flyspray/flyspray/assets/10474725/8db4bf61-d275-4771-b3e3-e243fd216bef)

[Flyspray 1.0-rc12 dev](https://www.flyspray.org/) latest [master branch](https://github.com/flyspray/flyspray/tree/master)

**Comment by CaraesNaur** [comment]
This is broken because the project pref `default_due_version` is stored as a version name (string).

When this string is passed to `tpl_options()` as the default to mark as selected, it can't match any of the version ids in the options array.

The quick fix that allows the pref to be stored properly (as an integer) is to change the third parameter to `tpl_options()` (`$labelIsValue`) from `true` to `false` (or remove it, as `false` is the default) in `templates/CleanFS/templates/pm.prefs.tpl`: (lines 101-107)

    <li>
        <label for="defaultdueversion"><?php echo Filters::noXSS(L('defaultdueinversion')); ?></label>
        <select id="defaultdueversion" name="default_due_version">
        <option value="0"><?= eL('undecided') ?></option>
        <?php echo tpl_options($proj->listVersions(false, 3), Post::val('default_due_version', $proj->prefs['default_due_version']), false); ?>
        </select>
    </li>

Line 105, just before the line ends.

All existing projects prefs will need to be updated again to affect the data change.

Then, the "Due In Version" `<select>` on New Task will render as expected, with the chosen default version selected.

> Well, perhaps... "Due In Version" includes Future versions (tense 3).  There is a valid use case for including Present versions (tense 2).



---

Longer term, a database adjustment is suggested to modify `projects.default_due_version` from `varchar(40)` to `int`.

**Comment by peterdd** [comment]
Done, thx.

`projects.default_due_version from varchar(40) to int`

 yeah migration to int seems logic
